version: "3.8"
services:
  db:
    container_name: mysql_playground_db
    image: mysql:latest
    restart: always
    env_file:
      - ./.env.local
    ports:
      - "3640:3306"
    volumes:
      - ./mysql:/var/lib/mysql
  pma:
    container_name: mysql_playground_pma
    image: phpmyadmin:latest
    restart: always
    ports:
      - "9090:80"
    links:
      - db
